dist: bionic
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"  

cache: pip

matrix:
  fast_finish: true
before_install:
  - pip install pytest-cov
install:
  - pip install -e ".[dev]"
script:
  - python -m pytest tests --cov=.
after_success:
  - pip install codecov
  - codecov
